services:
    backend-docker:
        build:
            context: ./backend/
            dockerfile: Dockerfile
        ports:
            - "3080:3080"
    frontend-docker:
        build:
            context: ./frontend/
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        depends_on:
            - backend-docker
